version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/var/www/html
        ports:
            - "8000:80"
        depends_on:
            - redis
            - db
        expose:
            -   "9000"

    redis:
        image: redis:7
        ports:
            - "6379:6379"

    db:
        image: postgres:15
        environment:
            POSTGRES_USER: blog_vue
            POSTGRES_PASSWORD: blog_vue
            POSTGRES_DB: blog_vue
        ports:
            - "5432:5432"

    nginx:
        build:
            context: .
            dockerfile: nginx.Dockerfile
        volumes:
            - ./src:/var/www/html
        ports:
            - "8080:80"
        environment:
            - NGINX_HOST=localhost
            - NGINX_PORT=80
        depends_on:
            - app
